const fs = require("fs");
const path = require("path");
const { PDFDocument } = require("pdf-lib");

async function convertImageToPDF() {
    try {
        const files = fs.readdirSync(__dirname);

        // Find the JPEG generated by the previous compression step
        const imageFile = files.find(file =>
            /\.(jpg|jpeg)$/i.test(file)
        );

        if (!imageFile) {
            console.log("No compressed JPEG found.");
            return;
        }

        const imagePath = path.join(__dirname, imageFile);
        const outputPath = path.join(
            __dirname,
            `${path.parse(imageFile).name}.pdf`
        );

        console.log("Using image:", imageFile);

        // Read compressed JPEG
        const imageBytes = fs.readFileSync(imagePath);

        // Create a new PDF
        const pdfDoc = await PDFDocument.create();

        // Embed JPEG
        const image = await pdfDoc.embedJpg(imageBytes);

        // Create page with same aspect ratio as image
        const scale = 1;

        const pageWidth = image.width * scale;
        const pageHeight = image.height * scale;

        const page = pdfDoc.addPage([
            pageWidth,
            pageHeight
        ]);

        // Draw image on the page
        page.drawImage(image, {
            x: 0,
            y: 0,
            width: pageWidth,
            height: pageHeight
        });

        // Save PDF
        const pdfBytes = await pdfDoc.save();

        fs.writeFileSync(outputPath, pdfBytes);

        console.log("JPEG successfully converted to PDF!");
        console.log("Output:", path.basename(outputPath));

        // Show PDF size
        const pdfSize = fs.statSync(outputPath).size;

        console.log(
            "PDF size:",
            (pdfSize / 1024).toFixed(2),
            "KB"
        );

    } catch (error) {
        console.error("Conversion failed:", error);
    }
}

convertImageToPDF();